CREATE DATABASE booking;

CREATE USER booking_app WITH PASSWORD 'pg';

\c booking

CREATE TABLE IF NOT EXISTS booking(
    ID         UUID PRIMARY KEY NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE   DATE NOT NULL
);

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO booking_app;
